### ISSUE TITLE
What service do we need to run before use?

### ISSUE THREAD

**Issue by Tokubara** [pingao777/markdown-preview-sync#13]
When executing `:MarkSyncPreview`, I get this error message:
```
Error detected while processing function mpsync#preview[2]..<SNR>178_start[11]..provider#python3#Call:
                                                                                                      
line   18:                                                                                            
Error invoking 'python_execute' on channel 4 (python3-script-host):                                   
Traceback (most recent call last):                                                                    
  File "<string>", line 3, in <module>                                                                
  File "/Users/quebec/.vim/plugged/markdown-preview-sync/autoload/python/java_vim_bridge.py", line 34,
 in start                                                                                             
    raise Exception('Fail to connect after ' + str(connect_cnt) + ' tries')                           
Exception: Fail to connect after 5 tries                                                              
Error detected while processing function mpsync#preview[5]..<SNR>178_open[18]..provider#python3#Call: 
line   18:                                                                                            
Error invoking 'python_execute' on channel 4 (python3-script-host):                                   
Traceback (most recent call last):                                                                    
  File "<string>", line 2, in <module>                                                                
  File "/Users/quebec/.vim/plugged/markdown-preview-sync/autoload/python/java_vim_bridge.py", line 45,
 in open                                                                                              
    s.sendall(wrap('open' + SEP + path + EOF))                                                        
BrokenPipeError: [Errno 32] Broken pipe 
```
Then I read source code, and I guess that the problem is in:
```python
_connect(port, theme)

def _connect(port, theme):
    global s
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.connect(('127.0.0.1', 23789))
    s.sendall(wrap('start' + SEP + str(port) + SEP + theme + EOF))
```
Then I execute `lsof -i:23789`:
```
COMMAND  PID   USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
Python  5694 quebec    7u  IPv4 0xac7436385164193f      0t0  TCP localhost:58733->localhost:23789 (CLOSED)
```
and find that port 23789 is close.
So is there a service we need to run before use so that we can connect successfully?

**Comment by naosense** [comment]
have you installed java？

**Comment by Tokubara** [comment]
I have figured it out. I gave wrong `g:markdown_preview_sync_chrome_path` settings(MacOS).
